version: '3.7'
services:
  iris:
    build:
      context: ./iris
    volumes:
      - ./iris:/tmp/iris
    commands: -a "sh server_start.sh"
    ports:
    - 52775:52773
    - 51776:1972
    - 52777:8080
  angular:
    build:
      context: ./angular
    ports:
      - 8080:80