version: '3.7'
services:
  iris:
    image: iris-ml
    build:
      context: ./iris
      args:
        - IRIS_PASSWORD=${IRIS_PASSWORD:-SYS}
    volumes:
      - ./iris:/tmp/iris
    ports:
    - 52775:52773
    - 51776:1972
    - 4040:8080
    - 4041:8081
  angular:
    build:
      context: ./angular
    ports:
      - 8080:80